version: 0.0
os: linux

files:
  - source: /
    destination: /opt/aivle-book-app

permissions:
  - object: /opt/aivle-book-app
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 0755
    type:
      - file
      - directory

hooks:
  AfterInstall:
    - location: deploy-scripts/after_install.sh
      timeout: 600
      runas: root

  ApplicationStop:
    - location: deploy-scripts/stop.sh
      timeout: 600
      runas: root

  ApplicationStart:
    - location: deploy-scripts/start.sh
      timeout: 600
      runas: root
