version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
      java: corretto17
    commands:
      - echo "Install dependencies"
  pre_build:
    commands:
      - echo "Build frontend (Next.js)"
      - cd book/frontend
      - npm ci
      - npm run build
      - cd ../..
      - echo "Build backend (Spring Boot)"
      - cd book
      - chmod +x ./gradlew
      - ./gradlew clean bootJar -x test
      - cd ..

artifacts:
  files:
    - appspec.yml
    - deploy-scripts/**/*
    - book/build/libs/*.jar

    - book/frontend/src/**/*
    - book/frontend/.next/**/*
    - book/frontend/public/**/*
    - book/frontend/package.json
    - book/frontend/package-lock.json
    - book/frontend/next.config.mjs